# Generated by Django 5.2.7 on 2025-10-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='x',
            field=models.TextField(default='teste'),
            preserve_default=False,
        ),
    ]
