# Generated by Django 5.2.7 on 2025-11-05 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_x'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'Opção', 'verbose_name_plural': 'Opções'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Questão', 'verbose_name_plural': 'Questões'},
        ),
    ]
